[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CLI"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = ["click"]

[project.scripts]
cli = "cli.cli_code:my_cli"

# [tool.uv]
# Package is at root level, not in "./src/".
# build-backend.module-root = ""
